# Generated by Django 4.1.7 on 2023-03-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_priceperperson_hotel_price_per_person_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="hotel_id",
            new_name="hotel",
        ),
    ]
