# Generated by Django 4.1.7 on 2023-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_hotel_id_image_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
