# Generated by Django 4.1.7 on 2023-03-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_hotel_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="image",
            name="hotel",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.hotel"
            ),
        ),
    ]
