# Generated by Django 4.1.7 on 2023-03-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_hotel_thumbnail_alter_image_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="thumbnail",
        ),
    ]
