# Generated by Django 4.1.7 on 2023-03-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_hotel_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="other_column",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
