# Generated by Django 4.1.7 on 2023-03-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_hotel_other_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="other_column",
        ),
    ]
