# Generated by Django 4.1.7 on 2023-03-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_rename_reservationstatusevents_reservationstatusevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="id",
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
