# Generated by Django 4.1.7 on 2023-03-31 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_remove_city_id_remove_hotel_id_remove_room_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="country",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
