# Generated by Django 4.1.7 on 2023-04-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_country_city_country_guest_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="city",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="country",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="city",
        ),
        migrations.RemoveField(
            model_name="image",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="invoiceguest",
            name="guest",
        ),
        migrations.RemoveField(
            model_name="invoiceguest",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest",
        ),
        migrations.RemoveField(
            model_name="reservationstatusevent",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="reservationstatusevent",
            name="reservation_status_catalog",
        ),
        migrations.RemoveField(
            model_name="reservedroom",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="reservedroom",
            name="room",
        ),
        migrations.RemoveField(
            model_name="room",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_type",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Guest",
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="InvoiceGuest",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.DeleteModel(
            name="ReservationStatusCatalog",
        ),
        migrations.DeleteModel(
            name="ReservationStatusEvent",
        ),
        migrations.DeleteModel(
            name="ReservedRoom",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="RoomType",
        ),
    ]
