# Generated by Django 4.1.7 on 2023-04-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_hotels",
                to="base.category",
            ),
        ),
    ]
