# Generated by Django 4.1.7 on 2023-04-02 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_alter_hotel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="service",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
