# Generated by Django 4.1.7 on 2023-04-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_hotel_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="star_rating",
            field=models.IntegerField(null=True),
        ),
    ]
