# Generated by Django 4.1.7 on 2023-04-04 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_hotel_star_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="star_rating",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
