# Generated by Django 4.1.7 on 2023-04-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_hotel_star_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country_hotels",
                to="base.country",
            ),
        ),
    ]
