# Generated by Django 4.1.7 on 2023-04-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_hotel_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="description",
        ),
        migrations.CreateModel(
            name="HotelDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_descriptions",
                        to="base.hotel",
                    ),
                ),
            ],
        ),
    ]
