# Generated by Django 4.1.7 on 2023-04-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_remove_hotel_description_hoteldescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteldescription",
            name="hotel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_descriptions",
                to="base.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="hoteldescription",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
