# Generated by Django 4.1.7 on 2023-04-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_remove_hotel_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteldescription",
            name="hotel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_description",
                to="base.hotel",
            ),
        ),
    ]
