# Generated by Django 4.1.7 on 2023-04-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_alter_hoteldescription_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteldescription",
            name="hotel",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_description",
                to="base.hotel",
            ),
        ),
    ]
