# Generated by Django 3.2.8 on 2023-04-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_hoteldescription_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
