# Generated by Django 3.2.8 on 2023-04-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20230410_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reserved_rooms', to='base.room'),
        ),
    ]
