# Generated by Django 3.2.8 on 2023-04-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_reservedroom_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservedRoom',
        ),
    ]
