# Generated by Django 3.2.8 on 2023-04-13 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_reservation_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='city',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 20, 6, 21, 482450, tzinfo=utc)),
        ),
    ]
