# Generated by Django 3.2.8 on 2023-04-13 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20230413_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id',
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 20, 23, 29, 354469, tzinfo=utc)),
        ),
    ]
