# Generated by Django 3.2.8 on 2023-04-13 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20230413_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 20, 52, 1, 611920, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservationstatuscatalog',
            name='status_name',
            field=models.CharField(choices=[('PEND', 'Pending'), ('CNCL', 'Cancelled'), ('CNFR', 'Confirmed')], max_length=4),
        ),
    ]
