# Generated by Django 3.2.8 on 2023-04-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20230413_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='expires_at',
        ),
    ]
