# Generated by Django 3.2.8 on 2023-04-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_reservation_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationstatusevent',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationstatusevent',
            name='reservation_status_catalog',
        ),
        migrations.DeleteModel(
            name='ReservationStatusCatalog',
        ),
        migrations.DeleteModel(
            name='ReservationStatusEvent',
        ),
    ]
