# Generated by Django 3.2.8 on 2023-04-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_reservationstatus_reservationstatusevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationstatusevent',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationstatusevent',
            name='reservation_status',
        ),
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
        migrations.DeleteModel(
            name='ReservationStatusEvent',
        ),
    ]
