# Generated by Django 3.2.8 on 2023-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_reservationstatus_reservationstatusevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationstatusevent',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationstatusevent',
            name='reservation_status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('CNCL', 'Cancelled'), ('CNFR', 'Confirmed')], default='PEND', max_length=4),
        ),
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
        migrations.DeleteModel(
            name='ReservationStatusEvent',
        ),
    ]
