# Generated by Django 3.2.8 on 2023-04-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20230415_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceguest',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='invoiceguest',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='InvoiceGuest',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
