# Generated by Django 3.2.8 on 2023-04-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_guest_invoiceguest_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='InvoiceGuest',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
