# Generated by Django 3.2.8 on 2023-04-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_invoiceguest_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceguest',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='invoiceguest',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='InvoiceGuest',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
