# Generated by Django 3.2.8 on 2023-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_guest_invoiceguest_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
