# Generated by Django 3.2.8 on 2023-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_roomtype_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceguest',
            name='time_canceled',
            field=models.DateTimeField(blank=True),
        ),
    ]
