# Generated by Django 3.2.8 on 2023-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_alter_invoiceguest_time_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceguest',
            name='time_canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
