# Generated by Django 3.2.8 on 2023-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_invoiceguest_time_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceguest',
            name='time_issued',
        ),
        migrations.AlterField(
            model_name='invoiceguest',
            name='time_paid',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
