# Generated by Django 3.2.8 on 2023-06-12 19:48

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20230612_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images', validators=[base.models.WebpValidator()]),
        ),
    ]
