# Generated by Django 3.2.8 on 2023-06-14 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='review_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
