# Generated by Django 3.2.8 on 2023-06-15 19:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_hotel_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('999999.99'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
